apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-servicebus
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: consumerID
    value: "shipments-processor-local-sub"     
  - name: connectionString # Required when not using Azure Authentication.
    value: ""
scopes:
- tracking-updates-processor